### ISSUE TITLE
[EPOS] Angi detaljer om datasettets arkivverdighet

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#136]
Som: datasetteier
Ønsker jeg å: angi detaljer om datasettets arkivverdighet
Slik at: dette gjøres ett sted og kan trekkes ut ifbm. avgivelse av datasett til Arkivverket

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by data-david** [comment]
Fra Arkvverket 6.9.2019

Da jeg var nede hos dere for å snakke om Arkivverkets arbeid mot Felles datakatalog, var vi inne på muligheten for å legge inn en fane/beskrivelse/funksjon eller noe, som angir om et datasett er vurdert for langtidsbevaring i en arkivinstitusjon, det være seg i Arkivverket, i en kommunal institusjon eller annet.

Etter dialog med fagseksjonen som behandler spørsmål om bevaring og kassasjon av offentlige og private arkiver, har vi kommet til at vi ønsker å be om en slik funksjon i datakatalogen.
Effekter av en slik funksjon vil være:

* Synliggjøring av hvilke data som vil være tilgjengelige, for forskning, sikring av rettigheter eller for videre og gjenbruk til andre formål enn det som var aktuelt mens dataene ble forvaltet av arkivskaper

* Synliggjøring av hvilke data som vil slettes og dermed ikke vil være tilgjengelige for ettertiden.

* Arkivverket vil få en bedre oversikt over hvilke datasett som er vurdert og kan bruke denne informasjonen ved utarbeidelse av bevaringsstrategien.

I tillegg til å angi om datasettet skal bevares eller slettes, ville det også være nyttig med en angivelse av hvor lenge data skal oppbevares fram til sletting etter overføring til arkivinstitusjon.
Det ville også være nyttig å kunne lenke til Arkivverkets register over bevarings- og kassasjonsvedtak, slik at beslutningen dels kan verifiseres og dels gi inspirasjon til andre virksomheter som med hjemmel i arkivloven §§ 9 og 12 og arkivforskriften §§ 14-16 er pålagt å vurdere sine datasett for bevaring, en vurdering som skal godkjennes av Riksarkivaren.

**Comment by KjerstiSteien** [comment]
Lukker denne saken frem til dette behovet er støttet i dcat-ap-no
