### ISSUE TITLE
[EPOS] Høste API-beskrivelser fra en API-management løsning

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#137]
Gitt at virksomheten har en API-management løsning i virksomheten
og at denne løsningen eksponerer samlingen av APIer på en standardisert måte
Som: virksomhetens Admin i APIkatalogens GUI
Ønsker jeg å: kunne sette opp høsting av min virksomhets API'er
Slik at: jeg kan få publisert APIene i Felles Datakatalog Portal

Forretningsverdi: Viktgi
Relatert til epos: #12 

Lenke til trådskisser: N/A
Lenke til løsningsarkitektur:
1) På virksomhetens side må noe(tm) sørge for å hente ut relevant info, og generere en katalogfil (ref #185) som FDK kan høste. Dette er parallellt til det som er laget for å hente begrepsbeskrivelser og generere SKOS-AP-NO fra BRs begrepskatalog i JIRA.
2) Mangler mekanisme for å styre tidspunkt for høsting/oppdatering i katalogen.

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag)
- [x] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Jeg mener dette behovet er løst. 
@KurtStian Hvis du er uenig, kan vi gjenåpne saken.
