### ISSUE TITLE
[EPOS] Begrep: Relasjoner

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#26]
Som: Skrivebruker
Ønsker jeg: å kunne lage sammenhenger i form av relasjoner mellom begreper 
Slik at: jeg kan dokumentere relaterte begreper.

Relatert til brukerhistorie: 
#72 
#83 
#84 
#85 
#88
#307 
#309 

Lenke til/beskrivelse av overordna arkitektur: denne løses ved at [api-et](https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml) må støtte relasjonsfelter. Det er litt ulik funksjonalitet knytta til dei ulike relasjonane, men dette går fram av respektive brukerhistorier.

Behovet/tiltaket vil gi…
- [x] betre brukaroppleving (inkluderer UU/wcag)
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by marittor** [comment]
Dette er for så vidt et behov som flere roller har. Standarden åpner for et knippe semantiske begresprelasjoner +"Se også"-relasjon og forvaltningsmessig relasjon "erstatter/erstattes av". Dette trenger vi støtte for å kunne registrere i registreringsløsningen.

**Comment by KjerstiSteien** [comment]
Regner denne som løst. Restanser løses i egne saker.
