### ISSUE TITLE
[EPOS] Begrepsregistrering - Utvidet funksjonalitet

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#329]
Som: skrivebruker
Ønsker jeg å: få mer funksjonalitet på plass, f. eks ekstra valgfrie felter og en kommentarfunksjon
Slik at: jeg får en mer fullverdig løsning å bruke

Tilknyttede brukerhistorier:
- [ ] #21  
#29 
#73
#75 
#80
#110
#175 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig 

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
@Te-Bert kan du se på denne og vurdere prioritet?

**Comment by KjerstiSteien** [comment]
Regner denne saken som løst, og løser resterende saker for seg.
