### ISSUE TITLE
[EPOS] Høsting til FDK på ulike formater

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#347]
Som: Skrivebruker (virksomhet)
Ønsker jeg å: kunne sette opp høsting og teste at høstingen fungerer, i tråd med Difis to forvaltningsstandarder for tilgjengligjøring av begrepsbeskrivelser
Slik at: begrepsbeskrivelser kan høstes av Felles begrepskatalog

Tilknyttede brukerhistorier:
- [x] #126 
#149 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [x] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
@Te-Bert kan du vurdere prioritet på det gjenstående arbeidet?
