### ISSUE TITLE
[EPOS] Tilgjengeliggjøring av begreper fra FDK på offisielle standarder

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#348]
Som: Felles datakatalog
Ønsker jeg å: eksponere begreper i tråd med Difis to forvaltningsstandarder for tilgjengeligjøring av begrepsbeskrivelser
Slik at: begrepsbeskrivelser kan eksponeres i Felles begrepskatalog så enkelt som mulig

Tilknyttede brukerhistorier:
- [x] #135 
#342 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
@Te-Bert kan du se på denne og vurdere prioritet?

**Comment by KjerstiSteien** [comment]
Lukker saken, da alle undersaker er lukket.
