### ISSUE TITLE
[EPOS] Bruk av Datasett (Datasettkatalog)

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#36]
Som bruker av datasett ønsker jeg *dialog med andre, bedre kunne se anvendelser og koblinger til andre ressurser* slik at jeg kan bedre forstå datasettet

Dette EPOSet utvider funksjonaliteten til datasettbeskrivelsene ut over behovet uttrykt i epos #32, #45, #42, #43 og #44 som ble levert i november 2017.

Gjenstående funksjonalitet (slettes når brukerhistoriene er koblet til)

- [x] - Dialogfunksjonalitet (dialog med bruker)
- [x] - Abonnement og varsling på endringer
- [x] - Knytte datasett til API 
- [x] - Nyhetsfunksjonalitet (twitter feed)
- [x] - Hieararkisk temaoversikt
- [ ] - Publisering til Google Dataset Search

**Comment by data-david** [comment]
https://github.com/orgs/Informasjonsforvaltning/projects/3#card-17009385

**Comment by data-david** [comment]
#32

**Comment by KjerstiSteien** [comment]
Publisering til Google dataset search er dekket av #94
