### ISSUE TITLE
[EPOS] Høste tjenestebeskrivelser fra felles tjenestekatalog

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#440]
Som: konsument av beskrivelser av tjenester
Ønsker jeg å: høste tjenestekataloger fra felles tjenestekatalog 
Slik at: jeg kan bruke beskrivelsene i løsningene til min virksomhet

Tilknyttede brukerhistorier:

Relatert til epos:
#1

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Annet: Utveksling med EU

**Comment by KjerstiSteien** [comment]
Lukker denne da det allerede finnes mulighet for å høste tjenestebeskrivelser fra felles tjenestekatalog i data.norge.no.
