### ISSUE TITLE
[EPOS] Integrasjon med virksomhetenes egne system for tilgangsstyring

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#68]
Som: virksomhet som bruker en eller flere løsninger i felles datakatalog som krever tilgangsstyring
Ønsker jeg å: enkel innlogging for mine ansatte og automatisk vedlikehold av hvem som har tilgang
Slik at: jeg slipper frustrerte ansatte som ikke tar løsningene i bruk og å bruke ressurser på vedlikehold

Tilknyttede brukerhistorier:
#625 
#627 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Behovet/tiltaket vil gi…
- [x] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Annet: Sikkerhet knyttet til tilgangskontroll.

**Comment by KjerstiSteien** [comment]
Løst for Brønnøysundsregistrene og Skatteetaten. Vi kommer nok ikke til å løse dette for flere, da det er krevende å både implementere og forvalte. Ser heller på en integrasjon mot ansattporten hvis det blir aktuelt. Enn så lenge får Altinn fungere som løsningen for de fleste virksomheter.
