### ISSUE TITLE
[EPOS] Høste tjenestebeskrivelser til felles tjenestekatalog

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#704]
Som: forvalter av en tjenestekatalog
Ønsker jeg å: høste vår tjenestekatalog til Felles datakatalog
Slik at: beskrivelsene av tjenestene i katalogen blir tilgjengeliggjort i Felles tjenestekatalog og kan være til nytte for andre

Tilknyttede brukerhistorier:
* #651 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [x] meir innhald og/eller betre kvalitet på innhald i FDK
- [x] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Andre: Del av medfinansieringssøknaden for tjenester og hendelser, SKATE-tiltak.

**Comment by KurtStian** [comment]
Lukker denne da brukerhistorien er løst/lukket.
