### ISSUE TITLE
[EPOS] Etablere en løsning for presentere informasjon om tjenester

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#705]
Som: konsument av en tjeneste
Ønsker jeg å: få oversikt over alle tjenester som er høstet til Felles datakatalog
Slik at: jeg kan oppdage, evaluere og bruke tjenester

Tilknyttede brukerhistorier:
* #650 
* https://github.com/Informasjonsforvaltning/behov/issues/945

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [x] meir innhald og/eller betre kvalitet på innhald i FDK
- [x] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Annet: Ekstern finansiering og SKATE-vedtak

**Comment by KjerstiSteien** [comment]
@BRespen @KurtStian hva er status på test her? Fint om vi kan beskrive restanser i egen sak og lukke denne.
