### ISSUE TITLE
[EPOS] Registrere hendelser i Felles hendelseskatalog

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#713]
Som: forvalter av en eller flere hendelser
Ønsker jeg å: registrere hendelser i Felles hendelseskatalog
Slik at: de blir dokumentert og tilgjengelig på et standardisert format

Tilknyttede brukerhistorier:
* #655 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [x] meir innhald og/eller betre kvalitet på innhald i FDK
- [x] betre samanheng mellom katalogprodukta 
- [x] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Annet: Ekstern finansiering, SKATE-vedtak
