### ISSUE TITLE
[BRUKERHISTORIE] Opprette og administrere interne felt i begrepskatalogen

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#788]
Som: virksomhet som skal bruke intern begrepskatalog
Ønsker jeg: å angi interne felter som er relevant for min virksomhet
Slik at: jeg kan forvalte intern informasjon jeg trenger å dokumentere

### Opprette interne felt
* Interne felt i denne sammenhengen er felt som er spesifikke for den enkelte virksomhet. 
* Bruker skal kunne angi navn for feltet, type felt. 
* Innhold i interne felt skal være søkbare i registreringsløsningen. 
* Interne felt skal aldri publiseres til portal. 

### Typer interne felt: 
* Tekstfelt kort
* Tekstfelt langt
* Boolsk verdi
* Kodeliste
* ~~Lenke~~

### Ønsker: 
~~Mulighet for å velge om interne felt skal vises i hoveddel av detaljside eller i høyre kolonne. (hvis enkelt)~~
~~Mulighet for å kunne knytte lenkefelt til tekstfelt (hvis enkelt) Eks: Kilde til Folkelig forklaring.~~
~~Mulighet til å kunne velge interne felt av typen kodelister eller boolsk verdi som filtre (dersom det ikke er veldig vanskelig å få til).~~

### Redigere interne felt
Navnet på feltet kan endres selv om feltet har innhold
Type felt kan ikke endres dersom det finnes innhold i feltet. 

### Slette interne felt
Interne felt som er i bruk skal kunne slettes, men bruker skal få en advarsel ved forsøk på sletting.
I advarselen skal bruker få beskjed om antall begrep som bruker feltet, helst med en liste over begrepene som bruker feltet.
Etter sletting skal feltet fjernes fra alle begrep som brukte feltet. 

Brukerhistorie hos BR: https://github.com/datautvikling/behov/issues/78

Relatert til epos: Informasjonsforvaltning/behov#792 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: 
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Er dette en uttømmende liste? Hvis ikke, kan vi få en fullstendig, prioritert liste som inneholder hvilke interne felt som er ønsket og hvilken type felt det skal være? Eks. fritekstfelt/kodeliste | | | |
|  | | | |

### Akseptansekriterier:

Gitt at jeg har administrasjonsrettigheter, så skal jeg kunne, 
- [x] opprette interne felt for min virksomhet
- [x] enkelt kunne se hvilken virksomhet sine interne felt jeg ser.
- [x] velge mellom følgende typer felt: Tekstfelt (kort), Tekstfelt (langt), Boolsk verdi, Kodeliste. 
- [x] velge hvilken kodeliste som skal brukes for felt av typen kodeliste. 
- [x] redigere navn på felt, uavhengig av om det finnes innhold i feltet. 
- [ ] redigere type felt som ikke har innhold i feltet. OBS! Det skal ikke være mulig å endre type felt dersom feltet har innhold.  
- [x] se en oversikt over hvilke interne felt min virksomhet har opprettet. 
- [x] slette interne felt som min virksomhet har opprettet. 
- [ ] ~~få opp en advarsel dersom jeg forsøker å slette et internt felt, med informasjon om hvor mange begrep som har innhold i feltet, helst med lenke til begrepene.~~
- [x] bekrefte at jeg ønsker å slette feltet. Dette skal føre til at feltet slettes fra alle begrep som bruker feltet. 
- [x] enkelt oppfatte om lagring/sletting er vellykket eller ikke.
- [ ] ~~se en oversikt over hvilke felles interne felt som er skrudd på for min virksomhet~~
- [ ] ~~aktivere eller deaktivere felles interne felt for min virksomhet enkeltvis.~~

Gitt at jeg har skrive/adminrettigheter, så skal jeg kunne se og fylle ut, 
- [x] interne felt på redigeringssiden
- [x] den typen informasjon som er spesifisert for de interne feltene
- [x] informasjon fra riktig kodeliste for interne felt som bruker kodelister. 

Gitt at jeg har lese/skrive/adminrettigheter, så skal jeg kunne se, 
- [x]  interne felt som er valgt i administrasjonsgrensesnittet på detaljsiden

### Test

[Testskjema](https://digdir.sharepoint.com/:x:/r/sites/FDKUtviklingsteam/Delte%20dokumenter/General/Akseptansetesting/Administrasjonsgrensesnitt/Begrepskatalogen/Interne%20felt.xlsx?d=wa7c85bfbb45747b5a6b693bc7acd15e8&csf=1&web=1&e=GD99c3&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0)

### Utviklingsoppgaver
- [x] Informasjonsforvaltning/fdk-issue-tracker#736
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/40
- [x] Informasjonsforvaltning/concept-catalog#190
- [x] Informasjonsforvaltning/catalog-frontend#140
- [x] Informasjonsforvaltning/concept-catalog-gui#533

**Comment by synnesol** [comment]
@KjerstiSteien formålet med denne brukerhistorien er at det vil oppstå ulike behov i ulike virksomheter. Vi ønsker å ha mulighet til å utvide interne felter. Vi må snakke om dette for å avklare behov og muligheter knyttet til denne brukerhistorien.

**Comment by KjerstiSteien** [comment]
@synnesol La oss ta en prat om dette etter nyttår.

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Skal det være mulig å repetere interne felt? Er det i så fall behov for å kunne velge om et internt felt skal være mulig å repetere eller ikke?

**Comment by jeffreiffers** [comment]
@synnesol @kristinekv Skal interne felt av type kodeliste støtte flere verdier eller kun en? Flere verdier er mer komplekst og krever mer tid å implementere.

**Comment by jeffreiffers** [comment]
@KjerstiSteien Trenger vi felt av type lenke som generell lenke eller skal dette alltid brukes som kilde? Hva med om hver type interne felt har et kilde felt i tillegg. Når kilde fylles ut blir den vist i detaljvisning.

**Comment by KjerstiSteien** [comment]
@kristinekv @synnesol Er kilde til merknad strengt nødvendig? Det kompliserer bildet litt. Se forøvrig spm til Jeff over om behov for generell lenke.

**Comment by kristinekv** [comment]
> @kristinekv @synnesol Er kilde til merknad strengt nødvendig? Det kompliserer bildet litt. Se forøvrig spm til Jeff over om behov for generell lenke.

Ikke for oss, vi bruker det ikke.

**Comment by kristinekv** [comment]
> @synnesol @kristinekv Skal interne felt av type kodeliste støtte flere verdier eller kun en? Flere verdier er mer komplekst og krever mer tid å implementere.

Vi har snakket om et hierarki for fagområde-kodeliste. Utover det tror jeg ikke trenger flere verdier.

**Comment by synnesol** [comment]
> @KjerstiSteien Trenger vi felt av type lenke som generell lenke eller skal dette alltid brukes som kilde? Hva med om hver type interne felt har et kilde felt i tillegg. Når kilde fylles ut blir den vist i detaljvisning.

tror ikke vi har noe annet felt som er av typen lenke enn det som er kilde. Trenger ikke kilde til interne felt.

**Comment by synnesol** [comment]
> @kristinekv @synnesol Er kilde til merknad strengt nødvendig? Det kompliserer bildet litt. Se forøvrig spm til Jeff over om behov for generell lenke.

Ikke strengt nødvendig, men det er i bruk i dag så da må det kanskje inn på kilde til definisjon. Vi har da behov for muligheten til å ha flere kilder på kilde til definisjon.

**Comment by synnesol** [comment]
> > @synnesol @kristinekv Skal interne felt av type kodeliste støtte flere verdier eller kun en? Flere verdier er mer komplekst og krever mer tid å implementere.
> 
> Vi har snakket om et hierarki for fagområde-kodeliste. Utover det tror jeg ikke trenger flere verdier.

Vi har også et behov for flere verdier på merkelapper

**Comment by synnesol** [comment]
> @synnesol @kristinekv Skal det være mulig å repetere interne felt? Er det i så fall behov for å kunne velge om et internt felt skal være mulig å repetere eller ikke?

Litt usikker på hva dere spør etter her

**Comment by KjerstiSteien** [comment]
Jeg tror egentlig jeg og Jeff spurte om det samme, men at jeg brukte bibliotekarsjargong. Du svarte ut det første jeg lurte på. 
Det andre jeg lurer på er om det er behov for å kunne angi om man skal kunne velge flere verdier i et internt felt.

**Comment by KjerstiSteien** [comment]
Eller det kan hende mitt første spm var litt videre enn Jeff sitt. Jeg lurer på om man skal kunne gjenta interne felt, eller om det kun skal være mulig å fylle ut én gang per språk. @jeffreiffers @NilsOveTen tar vi hensyn til språk på interne felt? 
@synnesol @kristinekv Burde vi det?

**Comment by synnesol** [comment]
> Eller det kan hende mitt første spm var litt videre enn Jeff sitt. Jeg lurer på om man skal kunne gjenta interne felt, eller om det kun skal være mulig å fylle ut én gang per språk. @jeffreiffers @NilsOveTen tar vi hensyn til språk på interne felt? @synnesol @kristinekv Burde vi det?

Jeg skjønner! Jeg klarer ikke komme på noen tilfeller der det er behov for å gjenta internt felt. For vår del trenger dere ikke ta hensyn til flere språk på internt felt. Når det er snakk om flere koder på internt felt, har vi ikke det behovet i dag, men jeg ser for meg at det i fremtiden kan dukke opp, for eksempel dersom vi ser behov for å ta inn bruksområde. Men da kan vi eventuelt ta den problemstillingen når den dukker opp.

**Comment by kristinekv** [comment]
> Eller det kan hende mitt første spm var litt videre enn Jeff sitt. Jeg lurer på om man skal kunne gjenta interne felt, eller om det kun skal være mulig å fylle ut én gang per språk. @jeffreiffers @NilsOveTen tar vi hensyn til språk på interne felt? @synnesol @kristinekv Burde vi det?

Vi har per nå bare oversettelser på anbefalt term, så multispråk på andre felter (interne og felles) er ikke nødvendig for oss. 

Det kan forekomme flere verdier på noen **felles** felt, som feks. eksempel og alternativ term. Disse kan fint løses med å bare skrive de med komma mellom. På de **interne** feltene trenger vi ikke mer enn en verdi på noen av feltene.

**Comment by KjerstiSteien** [comment]
Testresultat: Ok for lansering. Registrert bug på at man kan endre felttype for felt som er i bruk (burde ikke være mulig) https://github.com/Informasjonsforvaltning/catalog-frontend/issues/386
