### ISSUE TITLE
[BRUKERHISTORIE] Utvide søk til å søke i flere felter

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#789]
Som: leser i intern begrepskatalog
Ønsker jeg: at jeg kan velge hvilke felter det skal søkes i
Slik at: jeg får bedre treff

Se: https://github.com/datautvikling/behov/issues/85

Relatert til epos: Informasjonsforvaltning/behov#792 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=899%3A34682&viewport=520%2C695%2C0.5&scaling=min-zoom
Lenke til løsningsarkitektur:
Grovt estimat: 4-6 uker (avhengig av løsning)

### Detaljer:

Ved søk i søkefelt skal det søkes i alle felt. 

Det skal være mulig å begrense søket til: 
* søk i term (inkluderer feltene anbefalt term, frarådet term og tillatt term) 
* søk i definisjon og merknader (uklart om merknader er et eget felt)
### Avklaringer: 
Er det en mulighet for å huke av for å søke i flere felter? Hvis du f.eks. vil søke i term og definisjon, men de andre feltene.

Det skal være mulig å sortere trefflista etter:
* Anbefalt term (alfabetisk stigende)
* Anbefalt term (alfabetisk synkende)
* Sist endret-dato (stigende)
* Sist endret-dato (synkende)

Out of scope:
* Tildelt (alfabetisk stigende) _ikke nødvendig_
* Tildelt (alfabetisk synkende) _ikke nødvendig_
* Versjon (stigende) - _Ikke nødvendig_
* Versjon (synkende) - _Ikke nødvendig_

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Kan vi lage et søk som ikke inneholder vekting? Det vil gjøre både utvikling og drift av løsningen mye enklere for oss. | Det er ok å droppe vekting denne gangen, men ønsker en oversikt over kapasitet opp mot estimater, og en tydeligere forpliktelse til hva som kan leveres innenfor rammene som er satt.  | Synne Solbakken, Marit Torseth, Kristine Kvalnes | 14.12.2022 |
| Hvis man velger å søke i Anbefalt term, skal man da få treff i alle former for begrepsnavn/termnavn (eks: tidligere term, ikke foretrukket term, alternativ term etc)? | Hvis det er et valg å søke i "anbefalt term" bør du bare få treff i "anbefalt term". Men hvis valget er å søke i "term" er det greit at man får treff i "anbefalt term", "tillatt term" og "frarådet term" | | |

### Akseptansekriterier:

Gitt at jeg er logget inn, uavhengig av [rolle](https://github.com/Informasjonsforvaltning/behov/issues/790),
og jeg kunne gjøre følgende: 
1. Skrive inn et søkeord og kunne vise fram treff fra hvilket som helst av feltene (fra standard + interne felter)
2. Det skal også være mulig å avgrense søket til å søke i term, og få treff i anbefalt, frarådd term og tillatt term
3. Det bør være mulig å avgrense søket til å søke  i definisjon og merknad

TBD: Flere kriterier kommer etter at skisser er på plass
 
-------------------------------------------------------------------------------------------------------------------------------------
Issues for utvikling: 

- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/144
- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/143
- [x] Informasjonsforvaltning/catalog-frontend#139
- [x] Informasjonsforvaltning/catalog-frontend#141
- [x] Informasjonsforvaltning/catalog-frontend#142
- [x] Informasjonsforvaltning/catalog-frontend#143

**Comment by synnesol** [comment]
@KjerstiSteien vi ønsker en grundig forklaring på hvorfor vi ikke kunne ta i bruk elastic search eller lignende. Etter noen interne runder forstår vi fortsatt ikke hvorfor dette er estimert så høyt. Vi ser behovet for å koble på intern IT-kompetanse fra BR/skatt.

**Comment by marittor** [comment]
@KjerstiSteien - se for øvrig den tidligere brukerhistorien om tuning av søk her - https://github.com/Informasjonsforvaltning/behov/issues/54

**Comment by KjerstiSteien** [comment]
@synnesol @marittor Da sender vi dere noe rundt dette. Vi får ta opp dette igjen etter nyttår. Håper vi kan lande en endelig avklaring her.

**Comment by jeffreiffers** [comment]
Hvordan skal GUI til avansert søk se ut? Forventer dere noe som dette?
![image](https://user-images.githubusercontent.com/430997/209135599-662d94a1-9caa-4b17-9389-3188948a8818.png)

**Comment by KjerstiSteien** [comment]
@synnesol Vi lurer på om dere ser behov for å kunne sortere trefflista på versjonsnummer (alle begrep vil sorteres etter høyest eller lavest versjonsnummer mellom begrepene) og tildelt (sortering vil sorteres alfabetisk på tildelt. Vil behovet dekkes med filter for tildelt?) Hvis ikke så begrenser vi oss til å kunne sortere alfabetisk på anbefalt term og etter dato for sist endret. @kristinekv så ikke behov for dette.

**Comment by synnesol** [comment]
@KjerstiSteien denne har visst blitt borte for meg. Nei, jeg ser heller ikke behov for å sortere på tildelt og versjon.

**Comment by KjerstiSteien** [comment]
Til pre-refinement: Sjekk at vi støtter behovene som er beskrevet i saken - spør meg om dere lurer på noe. Lag issues på eventuelle mangler.

**Comment by jeffreiffers** [comment]
Testresultater
1. Paginering må nullstilles etter endring i søk
2. alle term felt mangler
3. tom søk skal returnere alle resultater
4. søk i definisjon og merknad feiler

**Comment by KjerstiSteien** [comment]
Testresultater

Paginering må nullstilles etter endring i søk - Testet ok. 
alle term felt mangler - Testet ok. 
tom søk skal returnere alle resultater - Testet ok. 
søk i definisjon og merknad feiler - Testet ok.

Test godkjent
