### ISSUE TITLE
[EPOS] Virksomhetsintern begrepskatalog

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#792]
Som: en virksomhet som tilbyr og konsumerer data
Ønsker jeg: en begrepskatalog for min virksomhet, der registrering av innhold, søk og gjenfinning henger sammen på "ett sted", på tvers av mine kataloger, uavhengig av om innholdet er publisert (og synlig for omverdenen) eller under arbeid (ev godkjent) og kun synlig for min virksomhet
Slik at: jeg kan gjøre meg kjent med begreper på en oversiktlig måte, der registrering, søk og gjenfinning er lett tilgjengelig.

Tilknyttede brukerhistorier:
- [x] https://github.com/Informasjonsforvaltning/behov/issues/791
- [x] https://github.com/Informasjonsforvaltning/behov/issues/790
- [x] https://github.com/Informasjonsforvaltning/behov/issues/789
- [x] https://github.com/Informasjonsforvaltning/behov/issues/788
- [x] https://github.com/Informasjonsforvaltning/behov/issues/787
- [x] https://github.com/Informasjonsforvaltning/behov/issues/786
- [x] https://github.com/Informasjonsforvaltning/behov/issues/785
- [x] https://github.com/Informasjonsforvaltning/behov/issues/784
- [x] https://github.com/Informasjonsforvaltning/behov/issues/783
- [x] https://github.com/Informasjonsforvaltning/behov/issues/676
- [x] https://github.com/Informasjonsforvaltning/behov/issues/677
- [x] https://github.com/Informasjonsforvaltning/behov/issues/680
- [x] https://github.com/Informasjonsforvaltning/behov/issues/794
- [x] https://github.com/Informasjonsforvaltning/behov/issues/793
- [x] #806
- [x] #807
- [x] #844
- [x] #843
- [x] #845
- [x] https://github.com/Informasjonsforvaltning/behov/issues/854

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

# Prioritert funksjonalitet ver. 1:
## Må ha: 
- [x] https://github.com/Informasjonsforvaltning/behov/issues/806
- [ ]
