### ISSUE TITLE
[Brukerhistorie] Treffliste

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#806]
Som: leser i intern begrepskatalog
Ønsker jeg: å få nok informasjon om begrepene jeg ser i trefflista
Slik at: jeg kan få oversikt over begrepene jeg har fått treff på.

Se: https://github.com/datautvikling/behov/issues/85

Relatert til epos: Informasjonsforvaltning/behov#792 
Relatert til brukerhistorie: Informasjonsforvaltning/behov#789 - Utvide søk til å søke i flere felter
Relatert til brukerhistorie: Informasjonsforvaltning/behov#791 - Filtrering i intern Begrepskatalog

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159%3A41103&viewport=-129%2C581%2C0.38&scaling=min-zoom  

Lenke til løsningsarkitektur:

### Detaljer
Følgende felt skal være synlig i trefflista: 
* Anbefalt term
* Sist endret-dato
* Begrepsstatus
* Publiseringstilstand i Felles datakatalog (vises kun dersom begrepet er publisert i Felles datakatalog)
* Fagområde (må ta høyde for inntil 4 nivåer)
* Begrepsansvarlig (tildelt)
* Definisjon (hele definisjonen skal vises i trefflista)
* Merkelapper (skal være klikkbare og føre til filtrering på merkelappen som er valgt)

### Out of scope for første leveranse:
* Informasjon om treff i skjulte felt (vurderer behovet underveis i utviklingen). 

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Til FDK: avklare om funksjonaliteter som paginering og sortering skal gjøres i backend | | | |
| | | | |

### Akseptansekriterier:

Gitt at jeg ... skal jeg kunne gjøre følgende: 

---------------------------------------------------------------------------------------------------------------------------------------
## Frontend:
- [x] Informasjonsforvaltning/concept-catalog-gui#470
- [x] Informasjonsforvaltning/concept-catalog-gui#490
- [x] Informasjonsforvaltning/concept-catalog-gui#489
- [x] Informasjonsforvaltning/concept-catalog-gui#488
- [x] Informasjonsforvaltning/concept-catalog-gui#487
- [x] Informasjonsforvaltning/concept-catalog-gui#486
- [x] Informasjonsforvaltning/concept-catalog-gui#485
- [x] Informasjonsforvaltning/concept-catalog-gui#483
- [x] Informasjonsforvaltning/concept-catalog-gui#482
- [x] Informasjonsforvaltning/concept-catalog-gui#481
- [x] Informasjonsforvaltning/concept-catalog-gui#492
- [x] Informasjonsforvaltning/concept-catalog-gui#484
- [ ] Informasjonsforvaltning/concept-catalog-gui#491
- [x] Informasjonsforvaltning/concept-catalog-gui#472

## Backend:
- [x] Informasjonsforvaltning/concept-catalog-gui#471

**Comment by KurtStian** [comment]
@KjerstiSteien Angående paginering - er det ikke snart på tide å også se på denne (støtte for å angi antall treff som skal vises per side) : https://github.com/Informasjonsforvaltning/behov/issues/686
Man kunne kanskje ha fått dette på plass først for denne trefflisten.

**Comment by KjerstiSteien** [comment]
@KurtStian Jo, det kan hende vi skal vurdere det. @NilsOveTen og @pooriamehregan hvor mye ekstra arbeid vil det innebære å få inn en mulighet for å velge hvor mange treff du vil se? Regner med at det er snakk om faste valg, f.eks. 10, 50, 100, Alle.

**Comment by NilsOveTen** [comment]
> @KurtStian Jo, det kan hende vi skal vurdere det. @NilsOveTen og @pooriamehregan hvor mye ekstra arbeid vil det innebære å få inn en mulighet for å velge hvor mange treff du vil se? Regner med at det er snakk om faste valg, f.eks. 10, 50, 100, Alle.

Hvis vi allerede legger til støtte for paginering så er det en neglisjerbar endring i backend å i tillegg ta med valg om hvor mange treff per side. I frontend kanskje litt mer, men tviler på at det er en spesielt stor jobb.

**Comment by pooriamehregan** [comment]
Tror en noenlunde grov estimat ville vært 2-4 dager i frontend. Mest sannsynlig går det fortere, likevel lite sjanse for at det tar lengre tid pga uforutsigbare ting som kan dukke opp underveis.

**Comment by kristinekv** [comment]
Resultat fra testing denne uka av skrivebruker og lesebruker: [FAK-81 Teste treffliste.pdf](https://github.com/Informasjonsforvaltning/behov/files/11965383/FAK-81.Teste.treffliste.pdf)

**Comment by jeffreiffers** [comment]
Svar på `FAK-81 Teste treffliste`:

- Filtrering på begrepsstatus, valgte filter vises ikke: SKAL RETTES
- Bug filtrering på feil side: SKAL RETTES
- Nytt begrep knapp fungerer OK hos oss (staging).
- Filtrering på navn og begrep: IKKE IMPLEMENTERT (kun frontend). Interne felt støtter ikke filtrering per i dag så dette må vurderes på nytt. Fjerner visning inn til videre.
- Nullstilling av søk. TRENGER AVKLARING
- Knapp `Legg til nytt begrep` vises ikke. Vises ikke når brukeren kun har lesetilgang.
- Knapp Ìmporter begrep` vises ikke. Vises ikke når brukeren kun har lesetilgang.
- Søk på termer får ikke treff på merknad tekst. Søk på termer søker i felter `anbefalt term`, `fradådet term` og `tillatt term`. Hvis man ønsker å søke i merknad må man velge `Merknad` felt.
- `Anbefalt term` vises som tittel på begrepet (se SKOS-AP-NO). `Frarådet` og `tillatt` term ser man i detaljvisningen til begrepet. Hvis søketeksten er tomt viser vi alle treff.
- Velge antall forekomster på en side: SKAL IMPLEMENTERES (ikke høy prio)
- Sortering på `anbefalt term`. Det finnes ikke noe som kalles anbefalt begrep. `Anbefalt term` er teksten som vises som tittel på begrepet (se SKOS-AP-NO)

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv skal det være mulig å filtrere på flere fagområder samtidig, eller holder det å kunne velge ett?

**Comment by KjerstiSteien** [comment]
Retest: 
Filtrering på begrepsstatus, valgte filter vises ikke: **Testet ok**
Bug filtrering på feil side: **Testet ok**
Nytt begrep knapp fungerer **Testet ok**
Filtrering på navn og begrep: **Testet ok**
Nullstilling av søk. **Restanse, løses senere (middels prio)**
Knapp Legg til nytt begrep vises ikke. Vises ikke når brukeren kun har lesetilgang. **Ok**
Knapp Ìmporter begrep` vises ikke. Vises ikke når brukeren kun har lesetilgang. **Ok**
Søk på termer får ikke treff på merknad tekst. Søk på termer søker i felter anbefalt term, frarådet term og tillatt term. Hvis man ønsker å søke i merknad må man velge Merknad felt. **Testet ok**
Anbefalt term vises som tittel på begrepet (se SKOS-AP-NO). Frarådet og tillatt term ser man i detaljvisningen til begrepet. Hvis søketeksten er tomt viser vi alle treff. **Ok**
Velge antall forekomster på en side: **Restanse, løses senere (lav prio)**
Sortering på anbefalt term. Det finnes ikke noe som kalles anbefalt begrep. Anbefalt term er teksten som vises som tittel på begrepet (se SKOS-AP-NO) **OK**

**Comment by KjerstiSteien** [comment]
Test godkjent
