### ISSUE TITLE
[BRUKERHISTORIE] Detaljside for begrep

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#807]
Som: lese- og skrivebruker av virksomhetsintern begrepskatalog
Ønsker jeg: å kunne se en oversiktlig detaljside tilknyttet et begrep
Slik at: jeg kun ser de feltene som er utfylt

Relaterte brukerhistorier:
- [x] Informasjonsforvaltning/behov#784 
- [x] Informasjonsforvaltning/behov#682 

Lenke til design: https://www.figma.com/proto/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?page-id=1%3A668&node-id=63-28833&viewport=961%2C578%2C0.2&scaling=scale-down-width

Lenke til løsningsarkitektur:

Akseptansekriterier
- [x] Oversiktlig og "dynamisk" oversikt over detaljene i et begrep på detaljsiden
- [x] All info, spesielt id, må være enkelt å markere og kopiere. 

--------------------------------------------------------------------------------------------------------------------------------------
## Tilknyttede saker/issues

- [x] Informasjonsforvaltning/catalog-frontend#23
- [x] Informasjonsforvaltning/catalog-frontend#28
- [x] Informasjonsforvaltning/catalog-frontend#27
- [x] Informasjonsforvaltning/catalog-frontend#26
- [x] Informasjonsforvaltning/catalog-frontend#25
- [x] Informasjonsforvaltning/catalog-frontend#24

**Comment by marittor** [comment]
@KjerstiSteien og @matfuru, kan dere legge lenke til trådskisse/ og evt. designskisse her, så vi kan gi tilbakemeldinger på den?

**Comment by KjerstiSteien** [comment]
@marittor @synnesol @kristinekv: Skulle vi flyttet akseptansekriteriene som gjelder visning av felt fra administrasjonsgrensesnittet til brukerhistorie for administrasjonsgrensesnittet? Jeg mener de henger tettere sammen med den brukerhistorien. Ved å flytte den kan vi lukke denne saken uavhengig av hvor vi står i utviklingen av administrasjonsgrensesnittet.

**Comment by KjerstiSteien** [comment]
> @KjerstiSteien og @matfuru, kan dere legge lenke til trådskisse/ og evt. designskisse her, så vi kan gi tilbakemeldinger på den?

Det kan vi gjøre. Mateus oppdaterer ila i morgen.

**Comment by matfuru** [comment]
Her er siste skisse:)
https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7525%3A157668&node-id=7850%3A180737&viewport=-6387%2C637%2C0.53&scaling=min-zoom

**Comment by matfuru** [comment]
Oppdatert skisse:
https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7525%3A157668&node-id=7880%3A163833&viewport=-6463%2C517%2C0.45&scaling=min-zoom&starting-point-node-id=7880%3A163833

**Comment by matfuru** [comment]
skissen er klikkbar: klikk på kommentarer/endringshistorikk

**Comment by matfuru** [comment]
Oppdatert skisse her. Skissen er klikkbar på kommentarer, endringshistorikk og versjoner: https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7525%3A157668&node-id=8181-163699&viewport=-5013%2C464%2C0.22&scaling=min-zoom&starting-point-node-id=7880%3A163833

**Comment by KjerstiSteien** [comment]
Design: 
* Se treffliste og detaljside i sammenheng - må ha samme look and feel. 
* Vurdere faner eller radioknapp for endringshistorikk, kommentarer etc. Eller er det behov for å kunne se begge samtidig? 
* Godkjent-status ser litt rart ut - gjøre noe med dette? 

Fremgangsmåte: 
* Kartlegge hva vi kan bruke av designsystemet.
* Avgjøre om vi skal bruke CSS modules eller style components.  
* Planlegge utvikling etter kartleggingen.

**Comment by KjerstiSteien** [comment]
@marittor @synnesol @kristinekv: vet ikke om dere så denne? 
Kan vi flyttet akseptansekriteriene som gjelder visning av felt fra administrasjonsgrensesnittet til brukerhistoriene for administrasjonsgrensesnittet? Jeg mener de henger tettere sammen med den brukerhistorien. Ved å flytte den kan vi lukke denne saken uavhengig av hvor vi står i utviklingen av administrasjonsgrensesnittet.

**Comment by kristinekv** [comment]
> @marittor @synnesol @kristinekv: vet ikke om dere så denne? Kan vi flyttet akseptansekriteriene som gjelder visning av felt fra administrasjonsgrensesnittet til brukerhistoriene for administrasjonsgrensesnittet? Jeg mener de henger tettere sammen med den brukerhistorien. Ved å flytte den kan vi lukke denne saken uavhengig av hvor vi står i utviklingen av administrasjonsgrensesnittet.

Ok for meg!

**Comment by marittor** [comment]
Det er helt okei!

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: kristinekv ***@***.***>
Sendt: Friday, June 23, 2023 8:00:56 AM
Til: Informasjonsforvaltning/behov ***@***.***>
Kopi: Torseth, Marit Holm ***@***.***>; Mention ***@***.***>
Emne: Re: [Informasjonsforvaltning/behov] [BRUKERHISTORIE] Detaljside for begrep (Issue #807)

ADVARSEL: Denne e-posten ble sendt fra en ekstern e-postadresse. Ikke trykk på lenker eller åpne vedlegg med mindre du kjenner til avsenderen og vet at innholdet er trygt


@marittor<https://github.com/marittor> @synnesol<https://github.com/synnesol> @kristinekv<https://github.com/kristinekv>: vet ikke om dere så denne? Kan vi flyttet akseptansekriteriene som gjelder visning av felt fra administrasjonsgrensesnittet til brukerhistoriene for administrasjonsgrensesnittet? Jeg mener de henger tettere sammen med den brukerhistorien. Ved å flytte den kan vi lukke denne saken uavhengig av hvor vi står i utviklingen av administrasjonsgrensesnittet.

Ok for meg!

**Comment by pooriamehregan** [comment]
Ser ut som alle issuene er ferdig i denne brukerhistorien. Kan saken lukkes? @KjerstiSteien

**Comment by KjerstiSteien** [comment]
Testet ok
