### ISSUE TITLE
[BRUKERHISTORIE] Håndtere felt knyttet til klasser/egenskaper som har utgått i SKOS-AP-NO v.2.0.3

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#834]
Som: Eier av Skos-ap-no
Ønsker jeg: at løsningene våre støtter oppdatert standard
Slik at: brukerne våre kan forholde seg til siste versjon av standarden.

Følgende felt utgår: 
| Klasse |KlasseURI | Egenskap | EgenskapsURI | I registreringsskjema? |
| ------ | ----------- | ---------- | ---------------- | ----- |
|Begrep |skos:Concept |Begrep - alternativ formulering | skosno:alternativFormulering | Nei |
|Begrep |skos:Concept |Begrep – bruksområde |skosno:bruksområde | Nei. Fjernet i 2023?|
|Term |skosxl:Label | - | - | Nei|
|Definisjon |skosno:Definisjon |Definition – sistOppdatert | dct:modified | Nei |
|Alternativ formulering |skosno:AlternativFormulering | - | - | Nei |
|Assosiativ relasjon |skosno:AssosiativRelasjon |Assosiativ relasjon – beskrivelse |dct:description | Ja. Innhold flyttes til Assosiativ relasjon - relasjonsrolle |
|Assosiativ relasjon |skosno:AssosiativRelasjon |Assosiativ relasjon – sistOppdatert |dct:modified | Nei |
|Generisk relasjon |skosno:GeneriskRelasjon |Generisk relasjon – sistOppdatert |dct:modified | Nei |
|Partitiv relasjon |skosno:PartitivRelasjon |Partitiv relasjon – sistOppdatert |dct:modified | Nei |

Nye felt: 
|Klasse|KlasseURI|Egenskap|EgenskapsURI|Verdiområde|Multiplisitet|Kravnivå|
| ----- | ---------- | -------- | --------------- | ------------- | ------------ | -------- |
| Begrep | skos:Concept | Begrep - dato opprettet | dct:created | xsd:date | 0..1 | Anbefalt |
| Begrep | skos:Consept | Begrep - ansvarlig virksomhet | dct:creator | org:Organization | 0..1 | Anbefalt |
| Begrep | skos:Concept | Begrep – publisert av | dct:publisher | org:Organization | 1..1 | Obligatorisk |
| Begrep |skos:Concept | Begrep – definisjon (direkte angivelse) | skos:definition | rdf:langString | 1..n | Obligatorisk |
| Begrep |skos:Concept | Begrep – er relatert til | skos:related | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – generaliserer | xkos:generalizes | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – spesialiserer | xkos:specializes | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – er del av | xkos:isPartOf | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – inneholder | xkos:hasPart | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – har eksakt samsvar med | skos:exactMatch | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – har nært samsvar med | skos:closeMatch | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – inngår i begrepssamling | uneskos:memberOf | skos:Collection | 0..n | Valgfri |
| Assosiativ relasjon | skosno:AssosiativRelasjon | Assosiativ begrepsrelasjon – relasjonsrolle | skosno:relationRole | skos:Concept or rdf:langString | 1..1 når skos:concept brukes 1..n når rdf:langString brukes | obligatorisk |

Som: Eier av Skos-ap-no
Ønsker jeg: å oppdatere klasse for egenskaper som har fått ny klasse i SKOS-AP-NO v2.0.3
Slik at: våre løsninger er i henhold til siste versjon av standarden.

Egenskaper med oppdatert URI: 
| Klasse i v1.1.1 |KlasseURI i v1.1.1| Egenskapsnavn i v1.1.1 |EgenskapsURI v1.1.1 | Flyttes til klasse i v2.0.3 | KlasseURI for ny klasse i v2.0.3 | Oppdatert egenskapsnavn i v2.0.3 | EgenskapsURI v2.0.3|
| ------ | ----------- | ---------- | ---------------- | ------------- | ------- | ------- | --------- |
|Definisjon |skosno:Definisjon |Definisjon – merknad | skos:scopeNote | Begrep | skos:Concept | Begrep – merknad | skos:scopeNote |
|Definisjon |skosno:Definisjon |Definisjon – eksempel | skos:example | Begrep | skos:Concept | Begrep – eksempel | skos:example |
|Definisjon |skosno:Definisjon |Definisjon – omfang |skosno:omfang | Begrep | skos:Concept | Begrep – verdiområde | skosno:valueRange |

Prioritering:
Start med anbefalte og obligatoriske felt.

Forslag til løsning:
Sjekk om det finnes innhold i felt for klasser/egenskaper som utgår. 
Hvis ikke det finnes innhold: Fjern feltet fra alle begrep og fra høsting/registrering/redigering. Husk å rydde opp etter rester i koden hvis aktuelt. 
Hvis det finnes: Støtte for å redigere og høste. Fjerne støtte for feltet i nyregistrering. 

Forslag til løsning:
Høsteløsning og portal bør støtte både oppdatert og tidligere URIer for egenskapene, klassene i høsting. 
Registreringsløsning oppdateres med ny URI for egenskaper/klasser. 
Alle begrep i registreringsløsning oppdateres med ny URI for egenskaper/klasser

Relatert til epos: Informasjonsforvaltning/behov#833 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

### Refinement

- [x] Informasjonsforvaltning/fdk-concept-harvester#127
- [x] Informasjonsforvaltning/concept-catalog#175
- [x] Informasjonsforvaltning/concept-catalog-gui#524
- [x] Informasjonsforvaltning/fdk-portal#1692
- [x] Informasjonsforvaltning/fdk-fulltext-search#264
- [x] #966
- [x] #967
- [x] #970
- [x] Flytte feltene "merknad" fra klassen "Definisjon" til klassen "Begrep"
- [x] Erstatte "definisjon - omfang" med "begrep - verdiområde".

**Comment by NilsOveTen** [comment]
Etter som jeg ser så har vi bruk av klassen `skosxl:Label` og egenskapen `dct:description` på klassen `skosno:AssosiativRelasjon` i registrering. Disse trenger vi mer informasjon om hvordan vi skal gå frem mtp data som er lagret, ellers kan vi fjerne eventuell støtte for alle de andre egenskapene/klassene i registrering.

**Comment by KurtStian** [comment]
Vi har også brukt egenskapen skosxl:literalForm i registreringsløsningen. Den er også implementert feil i registreringsløsningen da skosxl:literalForm kun kan ha en verdi per instans. Se eks.:
![image](https://user-images.githubusercontent.com/43232700/229109334-e9723dc2-b216-4332-881c-c4df71262fcb.png)

**skosxl:literalForm utgår og anbefalt term skal nå registreres direkte på skos:prefLabel** - https://data.norge.no/specification/skos-ap-no-begrep#Begrep-anbefalt-term

**Comment by Te-Bert** [comment]
Bruksområde utgår - eg. slås sammen med Fagområde
Eventuelt eksisterende innhold i Bruksområde flyttes derfor over til Fagområde

**Comment by KjerstiSteien** [comment]
Fra Terje på tidligere sak om nye felt: "Status" - valgfri
"Versjonsnummer" - valgfri
"Versjonsnote" - valgfri

**Comment by KjerstiSteien** [comment]
Fra Terje på tidligere sak om endring av klasse: Eksisterende Innhold i hhv eksempel, merknad, verdiområde under Definisjon, flyttes til tilsvarende under Begrep
(Samtidig må verdiområde under Begrep og tilllate nummerering slik at det kan angis en bestemt rekkefølge. men eksisterende innhold beholdes "flatt").
