### ISSUE TITLE
[BRUKERHISTORIE] Støtte høsting og visning av nye egenskaper i SKOS-AP-NO v2.0.3

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#835]
Som: Forvalter av Skos-ap-no
Ønsker jeg: at felt som er nye i standarden støttes av høsteløsningen og vises i portal
Slik at: virksomheter som bruker den nye standarden får feltene sine inn. 

Nye felt: 

|Klasse|KlasseURI|Egenskap|EgenskapsURI|Verdiområde|Multiplisitet|Kravnivå| Status |
| ----- | ---------- | -------- | --------------- | ------------- | ------------ | -------- | ---- |
| ~~Begrep~~ | skos:Concept | [Begrep - dato opprettet](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-dato-opprettet) | dct:created | xsd:date | 0..1 | Anbefalt | Støttes i json, portal mangler |
| Begrep | skos:Concept | [Begrep – ansvarlig virksomhet](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-ansvarlig-virksomhet) | dct:creator| org:Organization | 0..1 | Anbefalt| Ikke støttet |
| Begrep |skos:Concept | [Begrep – definisjon (direkte angivelse)](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-definisjon-direkte-angivelse) | skos:definition | rdf:langString | 1..n | Obligatorisk | Løst |
| Begrep |skos:Concept | [Begrep – er relatert til](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-er-relatert-til) | skos:related | skos:Concept | 0..n | Valgfri | Ikke støttet |
| Begrep |skos:Concept | [Begrep – generaliserer](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-generaliserer) | xkos:generalizes | skos:Concept | 0..n | Valgfri | Ikke støttet |
| Begrep |skos:Concept | [Begrep – spesialiserer](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-spesialiserer) | xkos:specializes | skos:Concept | 0..n | Valgfri | Ikke støttet |
| Begrep |skos:Concept | [Begrep – er del av](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-er-del-av) | xkos:isPartOf | skos:Concept | 0..n | Valgfri | Ikke støttet |
| Begrep |skos:Concept | [Begrep – inneholder](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-inneholder) | xkos:hasPart | skos:Concept | 0..n | Valgfri | Ikke støttet |
| ~~Begrep~~ |skos:Concept | [Begrep – har eksakt samsvar med](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-har-eksakt-samsvar-med) | skos:exactMatch | skos:Concept | 0..n | Valgfri | Støttet i json, portal mangler |
| ~~Begrep~~ |skos:Concept | [Begrep – har nært samsvar med](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-har-n%C3%A6rt-samsvar-med) | skos:closeMatch | skos:Concept | 0..n | Valgfri | Støttet i json, portal mangler  |
| ~~Begrep~~ |skos:Concept | [Begrep – inngår i begrepssamling](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-inng%C3%A5r-i) | uneskos:memberOf | skos:Collection | 0..n | Valgfri | Løst portal, mangler registrering |
| Begrep |skos:concept | [Begrep - publisert av](https://data.norge.no/specification/skos-ap-no-begrep#Begrep-publisert-av) - finnes allerede i FDK. Bytte label til Publisert av | dct:publisher | org:Organization | 1..1 | Obligatorisk | Løses senere ? |
| Assosiativ relasjon | skosno:AssosiativRelasjon | [Assosiativ begrepsrelasjon – relasjonsrolle] (https://data.norge.no/specification/skos-ap-no-begrep#Assosiativ-begrepsrelasjon-relasjonsrolle) | skosno:relationRole | skos:Concept or rdf:langString | 1..1 når skos:concept brukes 1..n når rdf:langString brukes | obligatorisk | Støtter rdf:langString, men ikke skos:concept |

Relatert til epos: Informasjonsforvaltning/behov#833 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

SKOS-AP-NO v2.0.3

---
**Backend**:
- [x] Informasjonsforvaltning/fdk-rdf-parser#253
- [x] Informasjonsforvaltning/fdk-fulltext-search#282
- [x] Informasjonsforvaltning/fdk-portal#1740
- [x] Informasjonsforvaltning/fdk-rdf-parser#258
- [x] Informasjonsforvaltning/fdk-portal#1749

---
**Relaterte issues**:
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/729

**Comment by NilsOveTen** [comment]
her kan vi nok starte på jobben i rdf-parser, portal bør vi ha skisser først

**Comment by Te-Bert** [comment]
+
"Status" - valgfri
"Versjonsnummer" - valgfri
"Versjonsnote" - valgfri

**Comment by pooriamehregan** [comment]
Hvis jeg leser dette korrekt så skal gamle `skosno:generiskRelasjon` blir nå `skosno:hasGenericConceptRelation ` i tillegg til at vi skal støtte direkte angivelse av relasjonen via `xkos:generalizes`.

Og at dette gjelder samtlige av relasjonstypene, og at vi derfor mangler `skosno:hasGenericConceptRelation ` osv i dette issuet.

Er det korrekt eller ligger det i et annet issue?

**Comment by pooriamehregan** [comment]
innspill fra @KurtStian :
Begrepet Boenhet har partitive relasjon (omfatter) mot Leilighet, men motsatt peker ikke blir satt.
F.eks.
Boenhet omfatter Leilighet. Hvis man går til leilighet så vises ikke den motsatt pekeren Leilighet er en del av Boenhet.
Dette vises heller ikke i portalen.

**Comment by KurtStian** [comment]
> innspill fra @KurtStian : Begrepet Boenhet har partitive relasjon (omfatter) mot Leilighet, men motsatt peker ikke blir satt. F.eks. Boenhet omfatter Leilighet. Hvis man går til leilighet så vises ikke den motsatt pekeren Leilighet er en del av Boenhet. Dette vises heller ikke i portalen.
---
Har forstått det slik at dette ikke er implementert fordi enkelte virksomheter ikke ville legge ut begrep hvis en annen virksomhet kunne si at sitt begrep var overordnet en annen virksomhet sitt begrep. Og så valgte man kanskje å midlertidig la være å vises motsatt peker. Kanskje fordi det kunne være forvirrende for en bruker å av og til se motsatt peker og av og til ikke. Men samtidig er det jo ikke bra at man kun ser relasjoner hvis man er inne på begrepet som relasjonen ble registrert på. Da blir det vanskelig å se hele bildet/begrepstrukturen.

Nå vurderes det om man kan bruke lisenser slik at en virksomhet kan angi om noen kan relatere til begrepet og bruke alle typene av relasjoner. Og da vises relasjonene begge veier.

**Comment by KurtStian** [comment]
Nye versjon av SKOS har fått navn på relasjonene for Partitiv og Generisk.

De nye navnene er:
- Generisk begrepsrelasjon – **har overbegrep** (skosno:hasGenericConcept)
- Generisk begrepsrelasjon – **har underbegrep** (skosno:hasSpecificConcept)
- Partitiv begrepsrelasjon – **har delbegrep** (skosno:hasPartitiveConcept)
- Partitiv begrepsrelasjon – **har helhetsbegrep** (skosno:hasComprehensiveConcept)

Registreringsløsning og portal bør oppdateres med de nye navnene.

**Comment by NilsOveTen** [comment]
Definisjon er løst ✔ 

Eget issue for created:
https://github.com/Informasjonsforvaltning/behov/issues/968

Eget issue for relasjoner:
https://github.com/Informasjonsforvaltning/behov/issues/971

Eget issue for creator/publisher:
https://github.com/Informasjonsforvaltning/behov/issues/969

Da dekker vi alt?
