### ISSUE TITLE
[BRUKERHISTORIE] Støtte registrering av nye egenskaper i SKOS-AP-NO v2.0.3

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#836]
Som: Begrepseier
Ønsker jeg: å kunne registrere egenskaper som er nye i SKOS-AP-NO v2.0.3
Slik at: jeg kan beskrive begrepene så presist som mulig, i henhold til nyeste versjon av standarden.

Nye felt: 
|Klasse|KlasseURI|Egenskap|EgenskapsURI|Verdiområde|Multiplisitet|Kravnivå|
| ----- | ---------- | -------- | --------------- | ------------- | ------------ | -------- |
| Begrep | skos:Concept | Begrep - dato opprettet | dct:created | xsd:date | 0..1 | Anbefalt |
| Begrep | skos:Consept | Begrep - ansvarlig virksomhet | dct:creator | org:Organization | 0..1 | Anbefalt |
| Begrep | skos:Concept | Begrep – publisert av | dct:publisher | org:Organization | 1..1 | Obligatorisk |
| Begrep |skos:Concept | Begrep – definisjon (direkte angivelse) | skos:definition | rdf:langString | 1..n | Obligatorisk |
| Begrep |skos:Concept | Begrep – er relatert til | skos:related | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – generaliserer | xkos:generalizes | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – spesialiserer | xkos:specializes | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – er del av | xkos:isPartOf | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – inneholder | xkos:hasPart | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – har eksakt samsvar med | skos:exactMatch | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – har nært samsvar med | skos:closeMatch | skos:Concept | 0..n | Valgfri |
| Begrep |skos:Concept | Begrep – inngår i begrepssamling | uneskos:memberOf | skos:Collection | 0..n | Valgfri |
| Assosiativ relasjon | skosno:AssosiativRelasjon | Assosiativ begrepsrelasjon – relasjonsrolle | skosno:relationRole | skos:Concept or rdf:langString | 1..1 når skos:concept brukes 1..n når rdf:langString brukes | obligatorisk |

Prioritering:
Start med anbefalte og obligatoriske felt.

Relatert til epos: Informasjonsforvaltning/behov#833 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

### Refinement
Forslag er å slå sammen Informasjonsforvaltning/behov#834, Informasjonsforvaltning/behov#836 og Informasjonsforvaltning/behov#839
- [ ] Informasjonsforvaltning/fdk-concept-harvester#127
- [ ] Informasjonsforvaltning/concept-catalog#175
- [ ] Informasjonsforvaltning/concept-catalog-gui#524
- [ ] Informasjonsforvaltning/fdk-portal#1692
- [ ] Informasjonsforvaltning/fdk-fulltext-search#264
- [ ]

**Comment by Te-Bert** [comment]
+
"Status" - valgfri
"Versjonsnummer" - valgfri
"Versjonsnote" - valgfri

**Comment by KjerstiSteien** [comment]
Dekkes av https://github.com/Informasjonsforvaltning/behov/issues/834
