### ISSUE TITLE
[BRUKERHISTORIE] Støtte endret klasse for egenskaper i SKOS-AP-NO v2.0.3

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#839]
Som: Eier av Skos-ap-no
Ønsker jeg: å oppdatere klasse for egenskaper som har fått ny klasse i SKOS-AP-NO v2.0.3
Slik at: våre løsninger er i henhold til siste versjon av standarden.

Egenskaper med oppdatert URI: 
| Klasse i v1.1.1 |KlasseURI i v1.1.1| Egenskapsnavn i v1.1.1 |EgenskapsURI v1.1.1 | Flyttes til klasse i v2.0.3 | KlasseURI for ny klasse i v2.0.3 | Oppdatert egenskapsnavn i v2.0.3 | EgenskapsURI v2.0.3|
| ------ | ----------- | ---------- | ---------------- | ------------- | ------- | ------- | --------- |
|Definisjon |skosno:Definisjon |Definisjon – merknad | skos:scopeNote | Begrep | skos:Concept | Begrep – merknad | skos:scopeNote |
|Definisjon |skosno:Definisjon |Definisjon – eksempel | skos:example | Begrep | skos:Concept | Begrep – eksempel | skos:example |
|Definisjon |skosno:Definisjon |Definisjon – omfang |skosno:omfang | Begrep | skos:Concept | Begrep – verdiområde | skosno:valueRange |

Forslag til løsning:
Høsteløsning og portal bør støtte både oppdatert og tidligere URIer for egenskapene, klassene i høsting. 
Registreringsløsning oppdateres med ny URI for egenskaper/klasser. 
Alle begrep i registreringsløsning oppdateres med ny URI for egenskaper/klasser

Relatert til epos: Informasjonsforvaltning/behov#833 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

### Refinement
Forslag er å slå sammen Informasjonsforvaltning/behov#834, Informasjonsforvaltning/behov#836 og Informasjonsforvaltning/behov#839
- [ ] Informasjonsforvaltning/fdk-concept-harvester#127
- [ ] Informasjonsforvaltning/concept-catalog#175
- [ ] Informasjonsforvaltning/concept-catalog-gui#524
- [ ] Informasjonsforvaltning/fdk-portal#1692
- [ ] Informasjonsforvaltning/fdk-fulltext-search#264

**Comment by Te-Bert** [comment]
Eksisterende Innhold i hhv eksempel, merknad, verdiområde under Definisjon, flyttes til tilsvarende under Begrep
(Samtidig må verdiområde under Begrep og tilllate nummerering slik at det kan angis en bestemt rekkefølge. men eksisterende innhold beholdes "flatt").

**Comment by KjerstiSteien** [comment]
Dekkes av https://github.com/Informasjonsforvaltning/behov/issues/834
