### ISSUE TITLE
[BRUKERHISTORIE] Opprette forslag til nytt begrep

### ISSUE THREAD

**Issue by synnesol** [Informasjonsforvaltning/behov#886]
Som: Lesebruker
Ønsker jeg å: opprette forslag til nytt begrep
Slik at: jeg kan komme med forslag til nye begrep jeg mener skal inn i intern begrepskatalog

Gitt at jeg som bruker av intern begrepskatalog (uavhengig av rolle) er inne i begrepskatalogen
SÅ skal jeg kunne trykke på en "nytt forslag"-knapp
SÅ skal det dukke opp en redigeringsside uten preutfylte felter
SÅ skal jeg kunne fylle ut alle felter jeg ønsker å fylle ut
SÅ skal jeg kunne trykke på en lagre-knapp

Gitt at jeg har trykket på lagre-knappen
SÅ skal det opprettes et nytt forslag som vises i treffliste for forslag
SÅ skal det sendes varsel (e-post?) til enten alle administratorer eller en eller flere utvalgte e-postadresser som er registrert i admin-grensesnittet

Relatert til epos:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..
-----------------------------------------------------------------------

Frontend:
- [x] Informasjonsforvaltning/catalog-frontend#168
- [x] [feature(concept:søk-detalj): knapp - foreslå endring](https://github.com/Informasjonsforvaltning/catalog-frontend/issues/170)
- [x] Informasjonsforvaltning/catalog-frontend#172
- [x] Informasjonsforvaltning/catalog-frontend#173
- [x] Informasjonsforvaltning/catalog-frontend#174
------------------------------------------------------------------------

Backend:
- [x] Informasjonsforvaltning/concept-catalog#204

Løsning: 
* Når lesebruker foreslår et nytt begrep regnes dette som et endringsforslag, det opprettes først et utkast når forslaget godkjennes av skrivebruker.

**Comment by synnesol** [comment]
@KjerstiSteien lagde en brukerhistorie på foreslå nytt begrep, kan du legge den til i prosjektet?

**Comment by KjerstiSteien** [comment]
Til pre-refinement: Se om det er mulig å planlegge/lage issues på deler av dette selv om design ikke er klart. Regner med at det krever en del endringer i backend? Eller er det allerede preppet for dette der?
