### ISSUE TITLE
[EPOS] Oppdatere rapportsidene

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#964]
Som: Virksomhet med pådriveransvar
Ønsker jeg: at rapportsidene skal være et godt verktøy for meg
Slik at: jeg enkelt kan avlese utviklingen på data.norge.no

## TODO: 
* Bedre løsning for statistikk, så vi kan stole på tallene grafene viser. 
* Mer enhetlig design på rapportsidene. 
* Vurdere brukerhistorier knyttet til rapportering

## Potensielle brukerhistorier:
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/558
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/487
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/486

Tidligere epos på området: 
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/400
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/485
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/441

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
