### ISSUE TITLE
[EPOS] Endring av registrering av kontaktinformasjon i registreringsløsning

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#965]
Som: Virksomhetsadministrator av registreringsløsningen
Ønsker jeg å: kunne styre hvilke muligheter skrivebrukere skal ha til å legge inn kontaktinformasjon
Slik at: jeg er trygg på at riktig kontaktinformasjon blir lagt på alle ressurser som registreres i løsningen. 

Tilknyttede brukerhistorier:
- [ ] Mulighet til å legge inn kontaktinformasjon for begrepskatalogen i administrasjonsgrensesnittet (MÅ)
- [ ] Mulighet til å velge om kontaktinformasjon skal hentes fra admingrensesnittet til registreringsskjema for begrep (MÅ)
- [ ] Mulighet til å velge om skrivebruker kan overstyre preutfylt informasjon i felt for kontaktinformasjon. 
- [ ] Tilsvarende som over for datasettkatalog, api-katalog, thk? Må sjekke spekk. 
- [ ] Felles kontaktinfo på tvers av kataloger? 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by kristinekv** [comment]
Vi ønsker å ha forskjellig kontaktinfor for forskellige kataloger.

**Comment by Lucialiuyang** [comment]
Vi har behov for både å kunne ha felles kontaktinfor for forskjellige kataloger og forskjellige kontaktinfo.
