### ISSUE TITLE
Erstatte "assosiativ relasjon - beskrivelse" til "assosiativ relasjon - relasjonsrolle" i registreringsløsning.

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#966]
## Nytt felt: Assosiativ relasjon - relasjonsrolle
|Klasse|KlasseURI|Egenskap|EgenskapsURI|Verdiområde|Multiplisitet|Kravnivå|
| ----- | ---------- | -------- | --------------- | ------------- | ------------ | -------- |
| Assosiativ relasjon | skosno:AssosiativRelasjon | Assosiativ begrepsrelasjon – relasjonsrolle | skosno:relationRole | skos:Concept or rdf:langString | 1..1 når skos:concept brukes 1..n når rdf:langString brukes | obligatorisk |

## Oppgaver:
- [x] Informasjonsforvaltning/behov#972
- [x] Informasjonsforvaltning/fdk-issue-tracker#917
- [x] Informasjonsforvaltning/fdk-issue-tracker#918
- [x] Informasjonsforvaltning/fdk-issue-tracker#919

**Comment by hegeaal** [comment]
![image](https://github.com/Informasjonsforvaltning/behov/assets/48259307/a046b626-068a-4f29-893a-6179b2e7eedc)
