### ISSUE TITLE
[EPOS] Støtte for kodeverkslignende datasett i Felles datakatalog 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#98]
Som: eier av et kodeverk/kodeliste
Ønsker jeg å: registrere beskrivelse av et kodeverk i Felles datakatalog
Slik at: andre kan få oversikt over hvilke kodeverk jeg eier og evt få tilgang for å gjenbruke 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Behovet/tiltaket vil gi…
- [x] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by marittor** [comment]
I gjeldende standard for datasettbeskrivelser (DCAT-AP-NO) finnes egenskapen Datasett:type. I tillegg ligger 'kodelister' som et valg under Datasett:type i registreringsløsningen til FDK. Altså kan man idag angi at et datasett er av typen kodeliste og dette vil (vel?) eksponeres under 'Bruk av datasettet' på detaljsiden i portalen. Et åpenbart behov her vil kunne være at man i tillegg kan filtrere på type som del av sidemeny i søkeside portal.

**Comment by oystein-asnes** [comment]
Denne må løses i standarden og har tatt den med over dit. https://github.com/difi/dcat-ap-no/issues/37

**Comment by stigbd** [comment]
Sidan det relaterte dcat-ap-no issuet er lukka, kan vi då lukke dette issuet, @oystein-asnes ?

**Comment by oystein-asnes** [comment]
Janei. FDK gir meg dette som tekststreng i turtle og ikkje URI-en. Her er range Skos concept. Eksempel frå[ Los-datasettet](https://data.norge.no/datasets/c479c6db-af9d-4467-a238-f30480d153e9): `dct:type "Taksonomi"` 
Her er det kontrollerte vokabularet som skal brukast: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/dataset-type 

Her har de/vi/nokon gjort eit utval som verkar fornuftig nok (men mulig det er fleire som skal med?). Typen "datasett" finst forresten ikkje i vokabularet, så litt usikker korleis vi skal angripe den.  Her manglar det også norske labels. ser eg. 

For å lukke denne bør ein vel også ha muligheit til å filtrere på datasett type på FDK.

**Comment by oystein-asnes** [comment]
Janei. FDK gir meg dette som tekststreng i turtle og ikkje URI-en. Her er range Skos concept. Eksempel frå[ Los-datasettet](https://data.norge.no/datasets/c479c6db-af9d-4467-a238-f30480d153e9): `dct:type "Taksonomi"` 
Her er det kontrollerte vokabularet som skal brukast: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/dataset-type 

Her har de/vi/nokon gjort eit utval som verkar fornuftig nok (men mulig det er fleire som skal med?). Typen "datasett" finst forresten ikkje i vokabularet, så litt usikker korleis vi skal angripe den.  Her manglar det også norske labels. ser eg. 

For å lukke denne bør ein vel også ha muligheit til å filtrere på datasett type på FDK.

**Comment by oystein-asnes** [comment]
Janei. FDK gir meg dette som tekststreng i turtle og ikkje URI-en. Her er range Skos concept. Eksempel frå[ Los-datasettet](https://data.norge.no/datasets/c479c6db-af9d-4467-a238-f30480d153e9): `dct:type "Taksonomi"` 
Her er det kontrollerte vokabularet som skal brukast: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/dataset-type 

Her har de/vi/nokon gjort eit utval som verkar fornuftig nok (men mulig det er fleire som skal med?). Typen "datasett" finst forresten ikkje i vokabularet, så litt usikker korleis vi skal angripe den.  Her manglar det også norske labels. ser eg. 

For å lukke denne bør ein vel også ha muligheit til å filtrere på datasett type på FDK.

**Comment by oystein-asnes** [comment]
Å seie at  `a dcat:Dataset `  er   `dct:type "datasett"` er vel smør på smør? Foreslår difor å fjerne "Datasett" som lovlig valg i registrerings-applikasjonen
